### ISSUE TITLE
SimCoupe on macOS Big Sur

### ISSUE THREAD

**Issue by jasehigh** [simonowen/simcoupe#33] opened 2020-12-05 17:06 UTC
Since upgrading the macOS Big Sur SimCoupe loads with a black screen and nothing works!

**Comment by simonowen** [comment] 2020-12-11 16:59
I don't currently have a Big Sur install available to reproduce this issue myself, but I'll see if I can set one up.

Does the application start correctly otherwise?  If you enter `BEEP 1,0` blindly after startup, do you hear a beep?

SimCoupe uses SDL2 for video, so it should pick an appropriate display API automatically. In newer code I'm trying OpenGL 3 before falling back on SDL2, which could possibly help, though I know Apple seems to be trying to move away from OpenGL support.

**Comment by jasehigh** [comment] 2020-12-11 17:15
Thanks for responding Simon... Yes if I enter `BEEP 1,0` blindly after startup I do hear the beep.

Jason.

**Comment by jasehigh** [comment] 2021-06-12 15:17
Is it possible to download the latest version for macOS?

**Comment by simonowen** [comment] 2021-06-14 19:49
Sorry for the lack of progress on this. I still don't have access to hardware that can run Big Sur to check it directly, and my attempts to install it on a VM have so far been unsuccessful. I'm limited to an old High Sierra installation at the moment and SimCoupe runs fine for me on that.

I don't think anything has changed in the code that would make it any better but I've created a fresh macOS build from the current code. Could you see if [this version](https://home.simonowen.com/SimCoupe-macOS-20210614.zip) works any better for you?  If not I'll probably need to find a developer with Big Sur access to take a look and see if they can diagnose it.

I have heard that Apple consider OpenGL to be deprecated on Big Sur, but I believe it should still work. The fact that SimCoupe starts at all should mean it believes the video system has been initialised and is working. I'll probably add Vulkan at some point, which should be a safer bet on most platforms in the future.

**Comment by jasehigh** [comment] 2021-06-14 21:21
Thanks for the reply... totally understand.

Unfortunately, the version shared crashes on Big Sur as soon as its run.

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 4A889CE9-8D7E-304E-A5F7-84D819B0BF9C
Library not loaded: @rpath/SAASound.framework/Versions/C/SAASound
  Referenced from: /Applications/SimCoupe.app/Contents/MacOS/SimCoupe
  Reason: image not found
```

**Comment by simonowen** [comment] 2021-06-15 07:56
It can't find the sound chip framework (SAASound) for some reason, though I can see it inside the application bundle in the zip. I have changed how that's built and bundled but I didn't think it should cause a problem. It runs fine for me but it's possible it found a different version elsewhere that I need to clean out for testing.

Right-click on the new SimCoupe app and select Show Package Contents, then browse into Frameworks. Try copying SAASound.framework from there into /Library/Frameworks/ to see if that helps it find it.

If that doesn't work, try removing the one from inside the package to leave just the system version.

If that doesn't work you could try copying SAASound.framework from an older SimCoupe, into both/either locations.

Failing that I'll have to see if building it using Xcode is different from the command-line method I'm using at the moment. The "@rpath" reference should be looking inside the application first, so it's odd that it's not finding it.

**Comment by davelaundon** [comment] 2021-06-15 21:19
Hi there. I just happened to be looking for the latest mac version of simcoupe tonight and came across this thread. I have not tried simcoupe on this mac (or any mac) before and downloaded from the link above.

Just to let you know that on Catalina I got the same error as Jason and copying the framework to /Library/Frameworks solved that (in fact I ended up doing all three frameworks).

However, now simcoupe just starts and exits straight away without anything coming up.

Let me know if there are any logs or anything I can do to assist debugging.

Dave.

**Comment by simonowen** [comment] 2021-06-16 20:07
Welcome back Dave!  I'd welcome any assistance looking at the immediate exit. I'd hope that something shows up in the Console app to report a failure, or maybe if you run `./SimCoupe.app/Contents/MacOS/SimCoupe` directly from a Terminal window. I'm not sure if there's a gdb available to run it through, but that would probably give even more detail at any crash/exit point.

The most likely reason for startup failure is probably due to video initialisation. Recent macOS builds should attempt to use OpenGL 3.x, falling back on the generic accelerated API via SDL2. It's a configuration I tested under Window as an SDL build, but I've not actually looked at which I'm getting under macOS, but it does run for me under High Sierra.

You could probably check whether any other libraries are missing by looking over the output of `otool -L ./SimCoupe.app/Contents/MacOS/SimCoupe`. Though I think missing libraries would probably give the same failure you got before moving the Frameworks around.

You could try building from source if you have Xcode and CMake installed. It should find the copied frameworks and use them as part of the build. I've been configuring my build as Unix Makefiles as it was the only way I could get a compiler with C++17 support to be used. My Xcode 9.3.x is the latest supported on High Sierra and it's too old to support some features. I actually stripped down my setup tonight and now it no longer builds at all. I really need to try and install a newer version of everything sometime. I had a Catalina VM but it stopped working when I switched to a new Ryzen system a few months ago.

Let me know if there's anything I can do from this side too, and thanks for looking!

**Comment by davelaundon** [comment] 2021-06-16 22:31
Hello Si :)

I'm a relative mac newb but I did manage to get some console output below. There is stuff going on in there all the time, but after spotting a couple of obvious SimCoupe entries I then filtered on its PID. Hopefully there is something in there that points you in the right direction!

default	23:05:48.616591+0100	com.apple.WebKit.Networking	boringssl_context_add_handshake_message_pending(578) [C6517.1:2][0x7fb2587a4860] Adding message(1)
default	23:06:38.165915+0100	mDNSResponder	[R79112->Q43367] AnswerQuestionByFollowingCNAME: 0x7f8d7d80ccb8 <private> (AAAA) following CNAME referral 2 for <private>
default	23:12:17.925123+0100	pkd	[d <private>] [u 995E4452-A3DB-428A-81B9-F0FFE3BD7870] [com.apple.share.System.set-buddy-picture(<private>)] Created plugin
default	23:12:17.925679+0100	pkd	[d <private>] [u DE0364D9-7774-4C46-9538-DB40DF03CBF1] [com.apple.share.System.set-account-picture(<private>)] Created plugin
default	23:18:29.716545+0100	runningboardd	_resolveProcessWithIdentifier sysctl pid 16591 is euid 502
default	23:18:29.716583+0100	runningboardd	Unable to obtain process properties from launchd for pid=16591
default	23:18:29.720980+0100	runningboardd	Resolved pid 16591 to [executable<SimCoupe(502)>:16591]
default	23:18:29.723011+0100	runningboardd	[executable<SimCoupe(502)>:16591] This process will not be managed.
default	23:18:29.723052+0100	runningboardd	Now tracking process: [executable<SimCoupe(502)>:16591]
default	23:18:29.723730+0100	runningboardd	Acquiring assertion targeting executable<SimCoupe(502)> from originator [daemon<com.apple.coreservices.launchservicesd>:146] with description <RBSAssertionDescriptor; foregroundApp:16591; ID: 322-146-1767; target: 16591> attributes = {
    <RBSDomainAttribute: 0x7fbb26d2f5f0; domain: com.apple.launchservicesd; name: RoleUserInteractiveNonFocal; sourceEnvironment: 0x0>;
}
default	23:18:29.724699+0100	runningboardd	Acquiring assertion targeting executable<SimCoupe(502)> from originator [daemon<com.apple.coreservices.launchservicesd>:146] with description <RBSAssertionDescriptor; foregroundApp:16591; ID: 322-146-1768; target: 16591> attributes = {
    <RBSDomainAttribute: 0x7fbb26e27b20; domain: com.apple.launchservicesd; name: RoleUserInteractiveNonFocal; sourceEnvironment: 0x0>;
}
default	23:18:29.724690+0100	runningboardd	[executable<SimCoupe(502)>:16591] Ignoring jetsam update because this process is not memory-managed
default	23:18:29.724981+0100	runningboardd	[executable<SimCoupe(502)>:16591] Ignoring resume because this process is not lifecycle managed
default	23:18:29.725023+0100	runningboardd	[executable<SimCoupe(502)>:16591] Set darwin role to: UserInteractiveNonFocal
default	23:18:29.725123+0100	runningboardd	[executable<SimCoupe(502)>:16591] Ignoring GPU update because this process is not GPU managed
default	23:18:29.802725+0100	distnoted	register name: AppleColorPreferencesChangedNotification object: kCFNotificationAnyObject token: f4242 pid: 16591
default	23:18:29.805025+0100	distnoted	register name: AppleAppSleepPreferencesChangedNotification object: kCFNotificationAnyObject token: f4243 pid: 16591
default	23:18:29.805788+0100	SimCoupe	FRONTLOGGING: version 1
default	23:18:29.805811+0100	SimCoupe	Registering, pid=16591
default	23:18:29.807461+0100	SimCoupe	CHECKIN: pid=16591
default	23:18:29.813330+0100	launchservicesd	CHECKIN:0x0-0x1d01d0 16591 $(PRODUCT_BUNDLE_IDENTIFIER)
default	23:18:29.813549+0100	SimCoupe	CHECKEDIN: pid=16591 asn=0x0-0x1d01d0 foreground=1
error	23:18:29.816564+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	23:18:29.816910+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	23:18:29.825427+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	23:18:29.826946+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	23:18:29.827425+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
default	23:18:29.827560+0100	tccd	PID[257] is checking access for target PID[16591]
error	23:18:29.827696+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	23:18:29.854937+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
default	23:18:29.860754+0100	SimCoupe	Registered, pid=16591 ASN=0x0,0x1d01d0
default	23:18:29.860924+0100	SimCoupe	Registered, pid=16591 cgConnectionID=81c2f
default	23:18:29.862703+0100	SimCoupe	BringForward: pid=16591 asn=0x0-0x1d01d0 bringForward=1 foreground=1 uiElement=0 launchedByLS=1 modifiersCount=1 allDisabled=0
default	23:18:29.862776+0100	SimCoupe	BringFrontModifier: pid=16591 asn=0x0-0x1d01d0 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
default	23:18:29.862849+0100	SimCoupe	BringForward: pid=16591 asn=0x0-0x1d01d0
default	23:18:29.863291+0100	launchservicesd	SETFRONT: pid=16591 asn=0x-0x1d01d0 foreground=1 oldFrontPid=7547 oldFrontASN=0x-0x1024250
default	23:18:29.862948+0100	SimCoupe	SetFrontProcess: asn=0x0-0x1d01d0 options=0
default	23:18:29.864365+0100	runningboardd	Acquiring assertion targeting executable<SimCoupe(502)> from originator [daemon<com.apple.coreservices.launchservicesd>:146] with description <RBSAssertionDescriptor; frontmost:16591; ID: 322-146-1769; target: 16591> attributes = {
    <RBSDomainAttribute: 0x7fbb26f37ff0; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
default	23:18:29.866990+0100	distnoted	register name: AppleInterfaceMenuBarHidingChangedNotification object: kCFNotificationAnyObject token: f4244 pid: 16591
default	23:18:29.871342+0100	runningboardd	[executable<SimCoupe(502)>:16591] Ignoring jetsam update because this process is not memory-managed
default	23:18:29.867413+0100	distnoted	register name: __NSFakeMemoryPressureNotification object: kCFNotificationAnyObject token: f4245 pid: 16591
default	23:18:29.871382+0100	runningboardd	[executable<SimCoupe(502)>:16591] Set darwin role to: UserInteractiveFocal
default	23:18:29.867492+0100	distnoted	register name: ApplePrivateInterfaceThemeChangedNotification object: kCFNotificationAnyObject token: f4246 pid: 16591
default	23:18:29.871412+0100	runningboardd	[executable<SimCoupe(502)>:16591] Ignoring GPU update because this process is not GPU managed
default	23:18:29.870528+0100	SimCoupe	Current system appearance, (HLTB: 2), (SLS: 1)
default	23:18:29.939899+0100	distnoted	register name: AppleAquaColorVariantChanged object: kCFNotificationAnyObject token: f4248 pid: 16591
default	23:18:29.959605+0100	distnoted	register name: AXInterfaceIncreaseContrastStatusDidChange object: kCFNotificationAnyObject token: f424b pid: 16591
default	23:18:29.959707+0100	distnoted	register name: AXInterfaceClassicInvertColorStatusDidChange object: kCFNotificationAnyObject token: f424c pid: 16591
default	23:18:29.959770+0100	SimCoupe	Post-registration system appearance: (HLTB: 2)
default	23:18:29.959769+0100	distnoted	register name: AXInterfaceDifferentiateWithoutColorStatusDidChange object: kCFNotificationAnyObject token: f424d pid: 16591
default	23:18:29.959826+0100	distnoted	register name: AXInterfaceReduceTransparencyStatusDidChange object: kCFNotificationAnyObject token: f424e pid: 16591
default	23:18:29.959883+0100	distnoted	register name: AXInterfaceReduceMotionStatusDidChange object: kCFNotificationAnyObject token: f424f pid: 16591
default	23:18:29.959940+0100	distnoted	register name: com.apple.universalaccess.screenPolarityDidChange object: kCFNotificationAnyObject token: f4250 pid: 16591
default	23:18:29.960001+0100	distnoted	register name: com.apple.universalaccess.screenGrayscaleDidChange object: kCFNotificationAnyObject token: f4251 pid: 16591
default	23:18:29.960061+0100	distnoted	register name: AppleInterfaceThemeChangedNotification object: kCFNotificationAnyObject token: f4253 pid: 16591
default	23:18:29.960217+0100	distnoted	register name: com.apple.universalaccess.VoiceOverSettingsDidChange object: kCFNotificationAnyObject token: f4255 pid: 16591
default	23:18:29.960288+0100	distnoted	register name: UniversalAccessDomainAssistiveControlSettingsDidChangeNotification object: kCFNotificationAnyObject token: f4257 pid: 16591
default	23:18:29.960344+0100	distnoted	register name: AppleNoRedisplayAppearancePreferenceChanged object: kCFNotificationAnyObject token: f425d pid: 16591
default	23:18:29.960401+0100	distnoted	register name: AppleNoRedisplayAppearancePreferenceChanged object: kCFNotificationAnyObject token: f425e pid: 16591
default	23:18:29.960459+0100	distnoted	register name: com.apple.AppleSpacesSwitchOnActivate object: kCFNotificationAnyObject token: f425f pid: 16591
default	23:18:29.970942+0100	distnoted	register name: NSEventResetDefaults object: com.apple.AppKit.NSEventResetDefaults token: f4264 pid: 16591
default	23:18:29.971035+0100	distnoted	register name: com.apple.AppleMultitouchTrackpadDomainDidChangeNotification object: kCFNotificationAnyObject token: f4265 pid: 16591
default	23:18:29.971103+0100	distnoted	register name: AppleEnableSwipeNavigateWithScrollsDidChangeNotification object: kCFNotificationAnyObject token: f4266 pid: 16591
default	23:18:29.971168+0100	distnoted	register name: AppleEnableMouseSwipeNavigateWithScrollsDidChangeNotification object: kCFNotificationAnyObject token: f4267 pid: 16591
default	23:18:29.971229+0100	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: $(PRODUCT_BUNDLE_IDENTIFIER) token: f4268 pid: 16591
default	23:18:29.973654+0100	distnoted	register name: AppleAquaAntiAliasingChanged object: kCFNotificationAnyObject token: f426b pid: 16591
default	23:18:29.974473+0100	distnoted	register name: com.apple.userkeyequivalentsdidchange object: kCFNotificationAnyObject token: f426c pid: 16591
default	23:18:29.975725+0100	distnoted	register name: com.apple.accessibility.api object: kCFNotificationAnyObject token: f426f pid: 16591
default	23:18:29.975745+0100	SimCoupe	Registering for test daemon availability notify post.
default	23:18:29.975925+0100	SimCoupe	notify_get_state check indicated test daemon not ready.
default	23:18:30.073353+0100	distnoted	register name: NSSecondaryDisplayVisChanged object: kCFNotificationAnyObject token: f4271 pid: 16591
default	23:18:30.074003+0100	distnoted	register name: NSPersistentUIBitmapEncryptionKeyDidChange object: kCFNotificationAnyObject token: f4273 pid: 16591
default	23:18:30.074326+0100	distnoted	register name: com.apple.nsquiet_safe_quit_give_reason object: $(PRODUCT_BUNDLE_IDENTIFIER) token: f4274 pid: 16591
default	23:18:30.075109+0100	distnoted	register name: AXInterfaceReduceTransparencyStatusDidChange object: kCFNotificationAnyObject token: f4275 pid: 16591
default	23:18:30.203332+0100	distnoted	register name: AppleAquaColorVariantChanged object: kCFNotificationAnyObject token: f4277 pid: 16591
default	23:18:30.203423+0100	distnoted	register name: AppleInterfaceThemeChangedNotification object: kCFNotificationAnyObject token: f4278 pid: 16591
default	23:18:30.203497+0100	distnoted	register name: AppleAquaAntiAliasingChanged object: kCFNotificationAnyObject token: f4279 pid: 16591
default	23:18:30.526868+0100	distnoted	register name: AXInterfaceIncreaseContrastStatusDidChange object: kCFNotificationAnyObject token: f427a pid: 16591
default	23:18:30.527400+0100	distnoted	register name: CGFontOverrideSettingsDidChange object: kCFNotificationAnyObject token: f427b pid: 16591
default	23:18:30.550678+0100	distnoted	register name: AppleNoRedisplayAppearancePreferenceChanged object: kCFNotificationAnyObject token: f427c pid: 16591
default	23:18:30.552251+0100	distnoted	register name: __NSFakeMemoryPressureNotification object: kCFNotificationAnyObject token: f427f pid: 16591
default	23:18:30.556052+0100	SimCoupe	SignalReady: pid=16591 asn=0x0-0x1d01d0
default	23:18:30.557761+0100	SimCoupe	SIGNAL: pid=16591 asn=0x0x-0x1901008
default	23:18:30.559951+0100	distnoted	register name: com.apple.Carbon.TISNotifyHandwritingInputSourceChanged object: kCFNotificationAnyObject token: f4280 pid: 16591
default	23:18:30.560033+0100	distnoted	register name: AppleTextInputMenuExtraDidLoadNotification object: kCFNotificationAnyObject token: f4281 pid: 16591
default	23:18:30.560094+0100	distnoted	register name: AppleKeyboardPreferencesSelectedItemsChangedNotification object: kCFNotificationAnyObject token: f4282 pid: 16591
default	23:18:30.560153+0100	distnoted	register name: com.apple.Carbon.TISNotifyEnabledKeyboardInputSourcesChanged object: kCFNotificationAnyObject token: f4283 pid: 16591
default	23:18:30.560213+0100	distnoted	register name: AppleLanguagePreferencesChangedNotification object: kCFNotificationAnyObject token: f4284 pid: 16591
default	23:18:30.560270+0100	distnoted	register name: com.apple.Carbon.TISNotifyHandwritingInputSourceChanged object: kCFNotificationAnyObject token: f4285 pid: 16591
default	23:18:30.560329+0100	distnoted	register name: com.apple.Carbon.TISNotifyIronwoodAutoEnableChanged object: kCFNotificationAnyObject token: f4286 pid: 16591
default	23:18:30.560395+0100	distnoted	register name: AppleInstalledInputSourcesChangedNotification object: kCFNotificationAnyObject token: f4287 pid: 16591
default	23:18:30.560516+0100	distnoted	register name: AppleEnabledInputSourcesChangedNotification object: kCFNotificationAnyObject token: f4288 pid: 16591
default	23:18:30.560625+0100	distnoted	register name: AppleSelectedInputSourcesChangedNotification object: kCFNotificationAnyObject token: f4289 pid: 16591
default	23:18:30.560761+0100	distnoted	register name: com.apple.Carbon.TISNotifyEnabledHandwritingLanguagesChanged object: kCFNotificationAnyObject token: f428a pid: 16591
default	23:18:30.560920+0100	distnoted	register name: com.apple.Carbon.TISNotifySelectedHandwritingLanguageChanged object: kCFNotificationAnyObject token: f428b pid: 16591
default	23:18:30.561050+0100	distnoted	register name: AppleRomanSwitchSettingChangedNotification object: kCFNotificationAnyObject token: f428c pid: 16591
error	23:18:30.563482+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	23:18:30.563889+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	23:18:30.567373+0100	tccd	Failed to copy signing info for 16591, responsible for file:///Applications/SimCoupe.app/Contents/MacOS/SimCoupe: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
default	23:18:30.765306+0100	distnoted	register name: AppleDatePreferencesChangedNotification object: kCFNotificationAnyObject token: f428d pid: 16591
default	23:18:30.765393+0100	distnoted	register name: AppleTimePreferencesChangedNotification object: kCFNotificationAnyObject token: f428e pid: 16591
default	23:18:30.765461+0100	distnoted	register name: AppleNumberPreferencesChangedNotification object: kCFNotificationAnyObject token: f428f pid: 16591
default	23:18:30.765522+0100	distnoted	register name: AppleTextBehaviorPreferencesChangedNotification object: kCFNotificationAnyObject token: f4290 pid: 16591
default	23:18:30.765580+0100	distnoted	register name: AppleKeyboardMenuPreferencesChangedNotification object: kCFNotificationAnyObject token: f4291 pid: 16591
default	23:18:30.765636+0100	distnoted	register name: AppleKeyboardPreferencesChangedNotification object: kCFNotificationAnyObject token: f4292 pid: 16591
default	23:18:30.765716+0100	distnoted	register name: AppleSelectedInputMethodPasteboardInvalidNotification object: kCFNotificationAnyObject token: f4293 pid: 16591
default	23:18:30.771923+0100	distnoted	register name: com.apple.Carbon.TISNotifySelectedKeyboardInputSourceChanged object: kCFNotificationAnyObject token: f4295 pid: 16591
default	23:18:30.783169+0100	SimCoupe	SetFrontProcess: asn=0x0-0x1d01d0 options=0
default	23:18:30.783652+0100	SimCoupe	WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.7 instead of 10.15.7. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
default	23:18:30.783756+0100	SimCoupe	0   CarbonCore                          0x00007fff3964bf22 ___Gestalt_SystemVersion_block_invoke + 112
default	23:18:30.783783+0100	SimCoupe	1   libdispatch.dylib                   0x00007fff722db658 _dispatch_client_callout + 8
default	23:18:30.783807+0100	SimCoupe	2   libdispatch.dylib                   0x00007fff722dc7de _dispatch_once_callout + 20
default	23:18:30.783829+0100	SimCoupe	3   CarbonCore                          0x00007fff395eddb8 _Gestalt_SystemVersion + 945
default	23:18:30.783896+0100	SimCoupe	4   CarbonCore                          0x00007fff395ed9cd Gestalt + 149
default	23:18:30.784007+0100	SimCoupe	5   SDL2                                0x00000001084bb66a SDL_Delay + 15722
default	23:18:30.784110+0100	SimCoupe	6   SDL2                                0x00000001084ece02 SDL_VideoInit + 866
default	23:18:30.785747+0100	distnoted	register name: com.apple.sharedfilelist.change object: com.apple.LSSharedFileList.ApplicationRecentDocuments token: f429a pid: 16591
default	23:18:30.785839+0100	distnoted	register name: com.apple.sharedfilelist.launch object: kCFNotificationAnyObject token: f429b pid: 16591
error	23:18:30.890185+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	23:18:30.890783+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
default	23:18:30.890899+0100	tccd	PID[16483] is checking access for target PID[16591]
error	23:18:30.891015+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	23:18:30.899200+0100	tccd	FAIL: PID[16591]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
default	23:18:30.973562+0100	launchservicesd	SETFRONT: pid=7547 asn=0x-0xfa0fa foreground=1 oldFrontPid=16591 oldFrontASN=0x-0x1901008
default	23:18:30.974231+0100	runningboardd	[executable<SimCoupe(502)>:16591] Death sentinel fired!
default	23:18:30.977572+0100	launchservicesd	QUITTING: pid=16591 asn=0x-0x1d01d0 foreground=1 wasFront=0
default	23:18:31.082344+0100	runningboardd	Removing process: [executable<SimCoupe(502)>:16591]
default	23:18:31.083056+0100	runningboardd	Removing assertions for terminated process: [executable<SimCoupe(502)>:16591]

**Comment by davelaundon** [comment] 2021-06-16 22:35
% otool -L /Applications/SimCoupe.app/Contents/MacOS/SimCoupe
/Applications/SimCoupe.app/Contents/MacOS/SimCoupe:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	@rpath/SAASound.framework/Versions/C/SAASound (compatibility version 3.0.0, current version 3.5.0)
	@executable_path/../Frameworks/reSID.framework/Versions/A/reSID (compatibility version 1.0.0, current version 1.0.0)
	@rpath/SDL2.framework/Versions/A/SDL2 (compatibility version 1.0.0, current version 11.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1561.20.106)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1450.16.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1129.5.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1450.16.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)

**Comment by simonowen** [comment] 2021-06-17 22:16
Thanks for the logs! Nothing much stands out in them as going wrong, except the final "Death sentinel fired!" message. Though Google suggests that's just some kind of wrapper terminating because the process has quit. There doesn't seem to be any sign of a crash or missing library, which fits the theory that video might be failing to initialise. I've always found Mac logs to be surprisingly noisy and scary looking even when everything is fine.

I managed to install Big Sur in a VM this evening and run the same tests. I got the same initial issue with framework locations, fixed by moving SAASound and SDL2 to /Library/Frameworks. I think reSID is fine because it uses the older @executable_path relative reference within the application bundle. The @rpath reference is the newer style which I think is supposed to support both application and system installation, but it's not working. That's a separate issue to look into...

I downloaded the Xcode command-line tools and built a new Debug version, and that showed the video was failing to initialise. However, that's probably expected for my VM case since there's no hardware accelerated video available and SimCoupe has *required* that for the last few years.

If you want to try the same test yourself, grab the Xcode command-line tools using `xcode-select --install`. Download CMake from cmake.org and install to /Applications. I'd also replace the SDL2.framework with a 2.0.14 from libsdl.org as the one I had is a bit old and throws up some warnings when building on Big Sur.  Grab and build using:

```
cd ~/Documents
git clone https://github.com/simonowen/simcoupe.git
mkdir simcoupe-build
cd simcoupe-build
/Applications/CMake.app/Contents/bin/cmake -DCMAKE_BUILD_TYPE=Debug ../simcoupe
make -j4
```

That should give you a local SimCoupe.app, albeit without the embedded frameworks. Run it from Terminal using: `./SimCoupe.app/Contents/MacOS/SimCoupe` and see if it reports anything. My version was terminating with "*error: Video initialisation failed*" output to the console, as expected. I'm going to try and get Big Sur on real hardware over the weekend to give a more reliable testing setup.

You could also try running it under the debugger using: `lldb ./SimCoupe.app/Contents/MacOS/SimCoupe`. Enter a breakpoint using `break set -n Video::Init`, then `r` to run. You can step over with `n` and step into with `si`. That might help show what is happening in more detail.

Compared to High Sierra the new OS version really doesn't like applications that aren't from the Mac App Store. As well as the initial running often requiring a right-click and Open to even start, I found it was reporting that the application needed permission to monitor the keyboard even when in the background. I don't know if that's just how SDL initialises the input but it required an option checking in System Preferences. It seemed to ask about every directory access the application did too, and there may be other prompts. The annual development fee and official store submission may be the only way around it.

**Comment by davelaundon** [comment] 2021-06-18 21:01
Thanks for the clear build steps! I followed everything and the built SimCoupe now runs. An error pops up in SimCoupe's UI saying Error loading SP0256 allophone data, whatever that is, but otherwise it seems to run ok!

So not sure if it is just the more up to date SDL version that fixed it?

In fact yes it is - I can now run the SimCoupe from earlier in this thread (which does not come up with the above error btw).

**Comment by simonowen** [comment] 2021-06-18 23:29
Thanks for the update! That sounds like progress, and I'd agree it's probably just the SDL2 update that's done the trick. Seems odd the old one doesn't still work but things seem to get deprecated much faster in macOS.

I fixed the missing allophone data in 8e37094639c960c2b3df37844de9a1a0db7fa66a, which is currently just in the `dev` branch. You can manually fix it by copying `sp0256-al2.bin` from the Resources directory in the source code to SimCoupe.app/Contents/Resources inside the application bundle. I copied it into the test version I built, but it'll be missing from your local copy.

I'll still need to look into the framework search issue but I think I can do that without needing it to start up completely. I did manage to get Big Sur installed on real hardware this evening, only to find the graphics card in that system is no longer supported so I'm still missing accelerated video support.

**Comment by simonowen** [comment] 2021-07-31 12:21
I've managed to get a real hardware setup and think I've fixed this.  Could you please try the [v1.2.1 dev release](https://github.com/simonowen/simcoupe/releases/tag/v1.2.1)?

If you could also try it without SAASound.framework and SDL2.framework in `/Library/Frameworks/` that would prove it's working stand-alone. You'll only need SDL2.framework in that location if you're building SimCoupe from source. Thanks!

The DMG doesn't currently have the normal fancy background, but I hope to return to using that or an equivalent in the future.

**Closed** 2021-08-09 16:50 UTC

**Comment by jasehigh** [comment] 2021-09-06 21:38
Apologies for not getting back to this sooner... Sim Coupe lives again on my Mac :-) Many thanks...

**Comment by simonowen** [comment] 2021-09-06 22:23
No worries, and thanks for confirming!
