### ISSUE TITLE
inaccurate frame rate

### ISSUE THREAD

**Issue by AntonyDTA** [simonowen/simcoupe#36] opened 2021-01-15 12:59 UTC
When SAA_Clock=8000000 and CPU_Clock=6000000, then
8000000/512*(2^Octave_0)/(511-Tone_199) = 6000000/119808
But in emulator, video frequency is not exactly equal to audio frequency.
I found that in SimCoupe, the video is delayed after sound by one frame in 31 seconds.
I didn't notice any latency in the real Sam.

Disk image: https://www.facebook.com/groups/20486797963/permalink/10158869915612964/

This disk image contains short test programs and the prototype of a 4-bit player at 11718 Hz.
"MOD_Play" is file with autostart.
Also "PhaseM .O" and "PhaseS .O".
This is the sound of the frequency generator and the sound generated by the program according to the video using the envelope.
M=Mono, tones are mixed
S=Stereo, tones are separated into left and right channel

**Comment by simonowen** [comment] 2021-01-17 23:07
Isn't that the expected difference because the CPU frequency doesn't exactly divide by the number of cycles per video frame?  6000000 CPU cycles per second / (384 cycles per second * 312 lines per frame) = 50.08 frames per second.  Over 31 seconds that means 1552 frames are generated, compared to 1551 frames if the frequency was exactly 50Hz.

More recent versions of SimCoupe use the audio for synchronisation, so the overall running speed should give the 50.08Hz. That's also assuming the audio hardware plays it exactly at the requested 44.1KHz rate, and that the SAA emulation is behaving as expected for the phase test you're performing. You could check with @stripwax for the last part?

**Comment by AntonyDTA** [comment] 2021-01-18 10:32
[debugsaa_PhaseS.zip](https://github.com/simonowen/simcoupe/files/5829459/debugsaa_PhaseS.zip)

100 periods of SAA sound (tone=199,octave=0) takes approximately 1.99678 seconds, which is 50.08063 Hz.
100 frames of the emulator takes approximately 1.9981 seconds, which is 50.04755 Hz.

**Comment by simonowen** [comment] 2021-06-14 22:44
I think this issue might be caused by the 3rd party Blip_Buffer component used by SimCoupe for its DAC support. I set the clock rate to 6000000 cycles and report 119808 cycles per SAM frame, but it's not giving the expected number of samples as output. I'd expect 44029.44 samples for 50 frames but I typically get 44058. That works out to be 50.04766Hz, which is almost exactly what you're reporting!

The DAC is used as a clock source for other audio components so the same number of samples is fetched from the SAA chip to match. That will cause the difference to the audio player, even when the SAA is emulated with a perfect 8MHz.

I'm not sure if it's something I can easily correct for but I'll take a closer look at Blip_Buffer. I know there are some accuracy constants available, and hopefully I can pick something that reduces or eliminates the difference.

**Comment by simonowen** [comment] 2021-06-15 17:18
I've just had a closer took at this and can see what's happening. Internally Blip_Buffer calculates a ratio between the output frequency (44100) and the time clock used by the caller (6000000 for CPU frequency in SimCoupe). This ratio is converted to a format of `N / (2 ^ BLIP_BUFFER_ACCURACY)` to be used for internal timing. That conversion will usually involve rounding, which means the frequency of output samples isn't exactly what you asked for.

In the current release of SimCoupe BLIP_BUFFER_ACCURACY is the default value of 16, and the approximate ratio calculated is 482 / 65536. Multiplying that back up gives an output sample rate of 44128.42 Hz, which is further out than I expected. The small frequency shift when playing back at 44100 will be hard to notice in most situations. Though driving the SAA (which is generating for 44100 Hz) directly from the CPU will expose the phase difference.

Increasing the BLIP_BUFFER_ACCURACY value in the denominator gives more resolution in the numerator. Increasing it to 20 means the ratio is 7707 / 1048576, which gives an output sample rate of 44099.82 Hz.  That's much closer and reduces the phasing period from 31 seconds that you're getting now to 3725 seconds, which is just over an hour.

Increasing the value further helps (well, from about 25), but the existing Blip_Buffer code doesn't support it. It uses 32-bit types internally and the change leaves too few bits for an offset. If I can convert the code to use 64-bit types we'll be able to increase it to 32, which gives output sample rate of 44100.0005 Hz. That should be good enough!

I'll report back when I've made the changes. I'll also need to check the difference it makes to sound processing, especially on 32-bit platforms.

**Comment by simonowen** [comment] 2021-06-24 17:55
I've just uploaded a [development release](https://github.com/simonowen/simcoupe/releases/tag/20210624-dev) that includes the fix for this. Hopefully it's much better than before!

**Closed by simonowen** 2021-06-24 17:55 UTC
