### ISSUE TITLE
.halted flag causes odd behaviour if you skip the HALT instruction in SimICE

### ISSUE THREAD

**Issue by gwinkless** [simonowen/simcoupe#18] opened 2020-01-14 19:28 UTC
In CheckInterrupt, this code is used to skip over the HALT instruction:

// Advance PC if we're stopped on a HALT
if (regs.halted)
{
PC++;
regs.halted = 0;
}
// Save the current PC on the stack
push(PC);

The problem is, if the user uses 
DI
HALT
EI
...
to bring up the ICE for debugging at a certain point, then skips over the HALT instruction, because of the way the HALT instruction is implemented

instr(4, 0166) regs.halted = 1; PC--; endinstr; // halt

the interrupts happen at a point that is not the HALT instruction - so you end up storing the wrong return address on the stack.

Suggest checking that the instruction at (PC) is 0x76 and not increasing PC if not - either that or adding code to the debugger to clear regs.halted when the user skips an instruction (probably the cleaner option).

**Comment by gwinkless** [comment] 2020-01-14 19:31
Ah. Issue 17 is the same. We both had the same idea :)

**Comment by simonowen** [comment] 2020-01-14 20:08
Shame I hadn't read your message before I looked into it, as we came to the same conclusion and solution!  Should be fixed in 666e5376fe29cfa0205bb73b3a5e2da652420867.

Are you building your own binaries from source? Since moving to CMake I've not yet created a minimal dependency (no CRT DLLs etc.) setup for official release builds.

**Comment by gwinkless** [comment] 2020-01-15 13:41
I'm not building from source; hardly use it these days, only created the issue because of the discussion that went on on the facebook group.

If I felt the need to scratch this particular itch and did decide to build from source, I'd probably prefer to use the free visual studio suite, just because it's on my machine already. I've never been a huge fan of cmake, it just seems like yet another set of tools to learn to use that don't really bring any advantage over make except to the person who wrote it because they didn't like the way make did things (cf systemd, iptools, iptables, &c &c &c).

**Comment by simonowen** [comment] 2020-01-15 17:22
Thanks for creating the issue. I'm not on Facebook so I wouldn't have known about it otherwise.

I'm using the free Community edition of Visual Studio 2019, which has CMake support built in. Make only really works for static build configurations, unless you have another build system that creates the Makefile. CMake isn't perfect but I think it's one of the better current build systems.  It's a vast improvement over the horrors of the auto* build tools.

**Comment by simonowen** [comment] 2020-01-15 19:35
Confirmed as fixed by 666e537.

**Closed by simonowen** 2020-01-15 19:35 UTC
