### ISSUE TITLE
Error reading disks with non ASCII Paths?

### ISSUE THREAD

**Issue by snail-coupe** [simonowen/simcoupe#74] opened 2022-01-14 21:09 UTC
I was getting track errors when trying to boot/dir some of my DSK files. After some experimentation I discovered all the problematic ones were in a folder called SimCoupé (note accent).  Renaming that folder to SimCoupe and they started working fine. Adding a á on the end broke them again.

I'm assuming something in the disk opening code isn't liking the accented characters.  This is on Win10 so I'm not certain if thats a codepage or WChar  or utf-8 thing or something else.

![simc0006](https://user-images.githubusercontent.com/53581981/149585456-170ef8ac-b319-4c38-b9d8-ce5cc03bbd14.png)
.

**Comment by simonowen** [comment] 2022-01-17 23:37
I thought I'd fixed this in #32 but it seems to have returned. It's caused by the same 3rd party library, which expects the path string for file_size to be in utf-8, despite Windows not using that encoding.

Changing it to use the real STL std::filesystem under Windows seems to fix it, so it should work again in the next release. Thanks for reporting!

**Comment by snail-coupe** [comment] 2022-01-18 20:44
Ah brill! Thanks

**Comment by simonowen** [comment] 2022-03-13 01:38
Fixed in new [v1.2.9 release](https://github.com/simonowen/simcoupe/releases/tag/v1.2.9).

**Closed by simonowen** 2022-03-13 01:38 UTC
